### ISSUE TITLE
Plugin no longer executes stream as of 6/29/21

### ISSUE THREAD

**Issue by jfpark** [eracknaphobia/plugin.video.nbcsnliveextra#4]
Plugin no longer executes stream as of 6/29/21
[kodi.log](https://github.com/eracknaphobia/plugin.video.nbcsnliveextra/files/6744615/kodi.log)

**Comment by eracknaphobia** [comment]
Confirmed. I'll take a look and see what can be done to fix it.

**Comment by jfpark** [comment]
Thank you so much for the reply and willingness to look into it!

**Comment by griffeyjuni0r** [comment]
Any hope for a fix in time for the Olympics coming up?

**Comment by sachinss123** [comment]
Yes please - I am facing the exact same errors (HTTP error 22 then 403). It would be great to use this to watch the Olympics on Kodi.

**Comment by eracknaphobia** [comment]
[Latest version](https://github.com/eracknaphobia/plugin.video.nbcsnliveextra/releases/tag/v2021.7.31) should fix the playback issue

**Comment by jfpark** [comment]
Latest version is still giving me an error on my PC install. 

2021.7.31+matrix.1

[kodi.log](https://github.com/eracknaphobia/plugin.video.nbcsnliveextra/files/6911320/kodi.log)

**Comment by sachinss123** [comment]
Thanks. Is there a Leia version? I cannot test this since it is only for Matrix.

**Comment by eracknaphobia** [comment]
@sachinss123 legacy version can be downloaded from here 
https://github.com/eracknaphobia/plugin.video.nbcsnliveextra/archive/refs/heads/legacy.zip

**Comment by sachinss123** [comment]
Thank you! It's not working for me. I'm getting the following log errors:

---------------

2021-08-03 11:02:43.815 T:3011822928   DEBUG: CGUIMediaWindow::GetDirectory (plugin://plugin.video.nbcsnliveextra/?icon_image=http%3a%2f%2fmobileassets.nbcsports.com%2ffiretv%2fchannels%2fnbcolympics-on.png&mode=4&name=Live&url=http%3a%2f%2fapi.leap.nbcsports.com%2ffeed%2fNBCSports%2fnbc-oly%2flive-upcoming%2fv1%2ffiretv)
2021-08-03 11:02:43.815 T:3011822928   DEBUG:   ParentPath = [plugin://plugin.video.nbcsnliveextra/?icon_image=http%3a%2f%2fmobileassets.nbcsports.com%2ffiretv%2fchannels%2fnbcolympics-on.png&mode=2&name=NBC%20Olympics&url=nbc-olympics]
2021-08-03 11:02:43.816 T:1816130416   DEBUG: Thread waiting start, auto delete: false
2021-08-03 11:02:43.827 T:1958732656   DEBUG: CAddonDatabase::SetLastUsed[plugin.video.nbcsnliveextra] took 12 ms
2021-08-03 11:02:43.827 T:1816130416   DEBUG: StartScript - calling plugin NBC Sports Live Extra('plugin://plugin.video.nbcsnliveextra/','64','?icon_image=http%3a%2f%2fmobileassets.nbcsports.com%2ffiretv%2fchannels%2fnbcolympics-on.png&mode=4&name=Live&url=http%3a%2f%2fapi.leap.nbcsports.com%2ffeed%2fNBCSports%2fnbc-oly%2flive-upcoming%2fv1%2ffiretv','resume:false')
2021-08-03 11:02:43.828 T:1984951152   DEBUG: Thread LanguageInvoker start, auto delete: false
2021-08-03 11:02:43.828 T:1984951152    INFO: initializing python engine.
2021-08-03 11:02:43.828 T:1984951152   DEBUG: CPythonInvoker(110, /storage/.kodi/addons/plugin.video.nbcsnliveextra/nbcsn.py): start processing
2021-08-03 11:02:43.853 T:1984951152   DEBUG: -->Python Interpreter Initialized<--
2021-08-03 11:02:43.853 T:1984951152   DEBUG: CPythonInvoker(110, /storage/.kodi/addons/plugin.video.nbcsnliveextra/nbcsn.py): the source file to load is "/storage/.kodi/addons/plugin.video.nbcsnliveextra/nbcsn.py"
2021-08-03 11:02:43.855 T:1984951152   DEBUG: CPythonInvoker(110, /storage/.kodi/addons/plugin.video.nbcsnliveextra/nbcsn.py): setting the Python path to /storage/.kodi/addons/plugin.video.nbcsnliveextra:/storage/.kodi/addons/script.module.adobepass/lib:/storage/.kodi/addons/script.module.certifi/lib:/storage/.kodi/addons/script.module.chardet/lib:/storage/.kodi/addons/script.module.idna/lib:/storage/.kodi/addons/script.module.kodi-six/libs:/storage/.kodi/addons/script.module.requests/lib:/storage/.kodi/addons/script.module.urllib3/lib:/usr/lib/python27.zip:/usr/lib/python2.7:/usr/lib/python2.7/plat-linux2:/usr/lib/python2.7/lib-tk:/usr/lib/python2.7/lib-old:/usr/lib/python2.7/lib-dynload:/usr/lib/python2.7/site-packages:/usr/lib/python2.7/site-packages/gtk-2.0
2021-08-03 11:02:43.855 T:1984951152   DEBUG: CPythonInvoker(110, /storage/.kodi/addons/plugin.video.nbcsnliveextra/nbcsn.py): entering source directory /storage/.kodi/addons/plugin.video.nbcsnliveextra
2021-08-03 11:02:43.855 T:1984951152   DEBUG: CPythonInvoker(110, /storage/.kodi/addons/plugin.video.nbcsnliveextra/nbcsn.py): instantiating addon using automatically obtained id of "plugin.video.nbcsnliveextra" dependent on version 2.19.0 of the xbmc.python api
2021-08-03 11:02:43.916 T:3011822928   DEBUG: ------ Window Init (DialogBusy.xml) ------
2021-08-03 11:02:44.255 T:1984951152   DEBUG: CAddonSettings[plugin.video.nbcsnliveextra]: loading setting definitions
2021-08-03 11:02:44.255 T:1984951152   DEBUG: CAddonSettings[plugin.video.nbcsnliveextra]: trying to load setting definitions from old format...
2021-08-03 11:02:47.208 T:1984951152   DEBUG: 1624028400
2021-08-03 11:02:47.231 T:1984951152   DEBUG: 1624231500
2021-08-03 11:02:47.233 T:1984951152   DEBUG: 1626825600
2021-08-03 11:02:47.234 T:1984951152   DEBUG: 1626836400
2021-08-03 11:02:47.236 T:1984951152   DEBUG: 1626847200
2021-08-03 11:02:47.237 T:1984951152   DEBUG: 1626852600
2021-08-03 11:02:47.238 T:1984951152   DEBUG: 1626854400
2021-08-03 11:02:47.241 T:1984951152   DEBUG: 1626856200
2021-08-03 11:02:47.298 T:1984951152   DEBUG: 1626863400
2021-08-03 11:02:47.364 T:1984951152   DEBUG: 1626865200
2021-08-03 11:02:47.366 T:1984951152   DEBUG: 1626867000
2021-08-03 11:02:47.367 T:1984951152   DEBUG: 1626912000
2021-08-03 11:02:47.368 T:1984951152   DEBUG: 1626922800
2021-08-03 11:02:47.369 T:1984951152   DEBUG: 1626933600
2021-08-03 11:02:47.370 T:1984951152   DEBUG: 1626939000
2021-08-03 11:02:47.371 T:1984951152   DEBUG: 1626940800
2021-08-03 11:02:47.373 T:1984951152   DEBUG: Previous line repeats 1 times.
2021-08-03 11:02:47.373 T:1984951152   DEBUG: 1626942600
2021-08-03 11:02:47.374 T:1984951152   DEBUG: 1626949800
2021-08-03 11:02:47.375 T:1984951152   DEBUG: 1626951600
2021-08-03 11:02:47.377 T:1984951152   DEBUG: Previous line repeats 1 times.
2021-08-03 11:02:47.377 T:1984951152   DEBUG: 1626953400
2021-08-03 11:02:47.378 T:1984951152   DEBUG: 1626996600
2021-08-03 11:02:47.414 T:1984951152   DEBUG: 1627038000
2021-08-03 11:02:47.481 T:1984951152   DEBUG: 1627083000
2021-08-03 11:02:47.514 T:1984951152   DEBUG: 1627084800
2021-08-03 11:02:47.526 T:1984951152   DEBUG: Previous line repeats 10 times.
2021-08-03 11:02:47.526 T:1984951152   DEBUG: 1627086000
2021-08-03 11:02:47.527 T:1984951152   DEBUG: 1627086600
2021-08-03 11:02:47.529 T:1984951152   DEBUG: Previous line repeats 1 times.
2021-08-03 11:02:47.529 T:1984951152   DEBUG: 1627088400
2021-08-03 11:02:47.535 T:1984951152   DEBUG: Previous line repeats 5 times.
2021-08-03 11:02:47.535 T:1984951152   DEBUG: 1627089300
2021-08-03 11:02:47.598 T:1984951152   DEBUG: 1627091100
2021-08-03 11:02:47.664 T:1984951152   DEBUG: 1627092000
2021-08-03 11:02:48.398 T:1984951152   DEBUG: Previous line repeats 15 times.
2021-08-03 11:02:48.398 T:1984951152   DEBUG: 1627189200
2021-08-03 11:02:48.998 T:1984951152   DEBUG: Previous line repeats 11 times.
2021-08-03 11:02:48.998 T:1984951152   DEBUG: 1627190100
2021-08-03 11:02:49.132 T:1984951152   DEBUG: Previous line repeats 1 times.
2021-08-03 11:02:49.132 T:1984951152   DEBUG: 1627190400
2021-08-03 11:02:49.265 T:1984951152   DEBUG: Previous line repeats 1 times.
2021-08-03 11:02:49.265 T:1984951152   DEBUG: 1627192800
2021-08-03 11:02:49.631 T:1984951152   DEBUG: Previous line repeats 9 times.
2021-08-03 11:02:49.631 T:1984951152   DEBUG: 1627193400
2021-08-03 11:02:49.665 T:1984951152   DEBUG: Previous line repeats 1 times.
2021-08-03 11:02:49.665 T:1984951152   DEBUG: 1627264800
2021-08-03 11:02:49.953 T:1984951152   DEBUG: Previous line repeats 17 times.
2021-08-03 11:02:49.953 T:1984951152   DEBUG: 1627347600
2021-08-03 11:02:50.598 T:1984951152   DEBUG: Previous line repeats 15 times.
2021-08-03 11:02:50.598 T:1984951152   DEBUG: 1627349400
2021-08-03 11:02:50.731 T:1984951152   DEBUG: Previous line repeats 1 times.
2021-08-03 11:02:50.731 T:1984951152   DEBUG: 1627351200
2021-08-03 11:02:51.248 T:1984951152   DEBUG: Previous line repeats 15 times.
2021-08-03 11:02:51.248 T:1984951152   DEBUG: 1627385400
2021-08-03 11:02:51.384 T:1984951152   DEBUG: Previous line repeats 5 times.
2021-08-03 11:02:51.384 T:1984951152   DEBUG: 1627386300
2021-08-03 11:02:51.515 T:1984951152   DEBUG: Previous line repeats 1 times.
2021-08-03 11:02:51.515 T:1984951152   DEBUG: 1627387200
2021-08-03 11:02:51.581 T:1984951152   DEBUG: Previous line repeats 3 times.
2021-08-03 11:02:51.581 T:1984951152   DEBUG: 1627389000
2021-08-03 11:02:51.715 T:1984951152   DEBUG: Previous line repeats 1 times.
2021-08-03 11:02:51.715 T:1984951152   DEBUG: 1627389900
2021-08-03 11:02:51.749 T:1984951152   DEBUG: Previous line repeats 1 times.
2021-08-03 11:02:51.749 T:1984951152   DEBUG: 1627390800
2021-08-03 11:02:51.783 T:1984951152   DEBUG: Previous line repeats 1 times.
2021-08-03 11:02:51.783 T:1984951152   DEBUG: 1627426800
2021-08-03 11:02:51.915 T:1984951152   DEBUG: Previous line repeats 1 times.
2021-08-03 11:02:51.915 T:1984951152   DEBUG: 1627428600
2021-08-03 11:02:52.015 T:1984951152   DEBUG: Previous line repeats 1 times.
2021-08-03 11:02:52.015 T:1984951152   DEBUG: 1627430400
2021-08-03 11:02:52.483 T:1984951152   DEBUG: Previous line repeats 13 times.
2021-08-03 11:02:52.483 T:1984951152   DEBUG: 1627432200
2021-08-03 11:02:52.715 T:1984951152   DEBUG: Previous line repeats 5 times.
2021-08-03 11:02:52.715 T:1984951152   DEBUG: 1627434000
2021-08-03 11:02:53.048 T:1984951152   DEBUG: Previous line repeats 9 times.
2021-08-03 11:02:53.048 T:1984951152   DEBUG: 1627435800
2021-08-03 11:02:53.081 T:1984951152   DEBUG: Previous line repeats 1 times.
2021-08-03 11:02:53.081 T:1984951152   DEBUG: 1627437600
2021-08-03 11:02:53.283 T:1984951152   DEBUG: Previous line repeats 5 times.
2021-08-03 11:02:53.283 T:1984951152   DEBUG: 1627469400
2021-08-03 11:02:53.448 T:1984951152   DEBUG: Previous line repeats 3 times.
2021-08-03 11:02:53.448 T:1984951152   DEBUG: 1627470000
2021-08-03 11:02:53.683 T:1984951152   DEBUG: Previous line repeats 7 times.
2021-08-03 11:02:53.683 T:1984951152   DEBUG: 1627471800
2021-08-03 11:02:53.848 T:1984951152   DEBUG: Previous line repeats 3 times.
2021-08-03 11:02:53.848 T:1984951152   DEBUG: 1627472700
2021-08-03 11:02:54.016 T:1984951152   DEBUG: Previous line repeats 3 times.
2021-08-03 11:02:54.019 T:1984951152   DEBUG: 1627473600
2021-08-03 11:02:54.181 T:1984951152   DEBUG: Previous line repeats 3 times.
2021-08-03 11:02:54.181 T:1984951152   DEBUG: 1627474500
2021-08-03 11:02:54.281 T:1984951152   DEBUG: Previous line repeats 1 times.
2021-08-03 11:02:54.281 T:1984951152   DEBUG: 1627475400
2021-08-03 11:02:54.316 T:1984951152   DEBUG: Previous line repeats 1 times.
2021-08-03 11:02:54.316 T:1984951152   DEBUG: 1627476300
2021-08-03 11:02:54.415 T:1984951152   DEBUG: Previous line repeats 1 times.
2021-08-03 11:02:54.415 T:1984951152   DEBUG: 1627477200
2021-08-03 11:02:54.515 T:1984951152   DEBUG: Previous line repeats 1 times.
2021-08-03 11:02:54.515 T:1984951152   DEBUG: 1627515000
2021-08-03 11:02:54.548 T:1984951152   DEBUG: Previous line repeats 1 times.
2021-08-03 11:02:54.548 T:1984951152   DEBUG: 1627516800
2021-08-03 11:02:54.581 T:1984951152   DEBUG: Previous line repeats 1 times.
2021-08-03 11:02:54.582 T:1984951152   DEBUG: 1627603200
2021-08-03 11:02:54.915 T:1984951152   DEBUG: Previous line repeats 9 times.
2021-08-03 11:02:54.915 T:1984951152   DEBUG: 1627604100
2021-08-03 11:02:55.048 T:1984951152   DEBUG: Previous line repeats 1 times.
2021-08-03 11:02:55.048 T:1984951152   DEBUG: 1627605000
2021-08-03 11:02:55.118 T:1984951152   DEBUG: Previous line repeats 3 times.
2021-08-03 11:02:55.118 T:1984951152   DEBUG: 1627605900
2021-08-03 11:02:55.248 T:1984951152   DEBUG: Previous line repeats 1 times.
2021-08-03 11:02:55.248 T:1984951152   DEBUG: 1627606800
2021-08-03 11:02:55.481 T:1984951152   DEBUG: Previous line repeats 7 times.
2021-08-03 11:02:55.481 T:1984951152   DEBUG: 1627697100
2021-08-03 11:02:55.581 T:1984951152   DEBUG: Previous line repeats 1 times.
2021-08-03 11:02:55.582 T:1984951152   DEBUG: 1627698600
2021-08-03 11:02:55.648 T:1984951152   DEBUG: Previous line repeats 1 times.
2021-08-03 11:02:55.648 T:1984951152   DEBUG: 1627802700
2021-08-03 11:02:55.715 T:1984951152   DEBUG: 1627804800
2021-08-03 11:02:55.781 T:1984951152   DEBUG: 1627948800
2021-08-03 11:02:56.198 T:1984951152   DEBUG: Previous line repeats 7 times.
2021-08-03 11:02:56.198 T:1984951152   DEBUG: 1627950000
2021-08-03 11:02:56.265 T:1984951152   DEBUG: Previous line repeats 1 times.
2021-08-03 11:02:56.265 T:1984951152   DEBUG: 1627950600
2021-08-03 11:02:56.498 T:1984951152   DEBUG: Previous line repeats 3 times.
2021-08-03 11:02:56.498 T:1984951152   DEBUG: 1627952400
2021-08-03 11:02:56.998 T:1984951152   DEBUG: Previous line repeats 9 times.
2021-08-03 11:02:56.998 T:1984951152   DEBUG: 1627954200
2021-08-03 11:02:57.098 T:1984951152   DEBUG: Previous line repeats 1 times.
2021-08-03 11:02:57.098 T:1984951152   DEBUG: 1628073000
2021-08-03 11:02:57.298 T:1984951152   DEBUG: Previous line repeats 3 times.
2021-08-03 11:02:57.298 T:1984951152   DEBUG: 1628074200
2021-08-03 11:02:57.386 T:1984951152   DEBUG: Previous line repeats 3 times.
2021-08-03 11:02:57.386 T:1984951152   DEBUG: 1628075700
2021-08-03 11:02:57.434 T:1984951152   DEBUG: Previous line repeats 1 times.
2021-08-03 11:02:57.435 T:1984951152   DEBUG: 1628077500
2021-08-03 11:02:57.565 T:1984951152   DEBUG: Previous line repeats 1 times.
2021-08-03 11:02:57.565 T:1984951152   DEBUG: 1628338500
2021-08-03 11:02:57.665 T:1984951152   DEBUG: Previous line repeats 1 times.
2021-08-03 11:02:57.665 T:1984951152   DEBUG: 1628373600
2021-08-03 11:02:57.767 T:1984951152   DEBUG: Previous line repeats 1 times.
2021-08-03 11:02:57.767 T:1984951152   DEBUG: 1628380800
2021-08-03 11:02:57.932 T:1984951152   DEBUG: Previous line repeats 1 times.
2021-08-03 11:02:57.932 T:1984951152   DEBUG: 1628382600
2021-08-03 11:02:57.966 T:1984951152   DEBUG: Previous line repeats 1 times.
2021-08-03 11:02:57.966 T:1984951152   DEBUG: 1628384400
2021-08-03 11:02:58.098 T:1984951152   DEBUG: Previous line repeats 1 times.
2021-08-03 11:02:58.098 T:1984951152   DEBUG: 1628388000
2021-08-03 11:02:58.234 T:1984951152   DEBUG: Previous line repeats 5 times.
2021-08-03 11:02:58.235 T:1984951152   DEBUG: 1628389800
2021-08-03 11:02:58.365 T:1984951152   DEBUG: Previous line repeats 1 times.
2021-08-03 11:02:58.365 T:1984951152   DEBUG: 1628397000
2021-08-03 11:02:58.465 T:1984951152   DEBUG: Previous line repeats 1 times.
2021-08-03 11:02:58.465 T:1984951152   DEBUG: 1628397600
2021-08-03 11:02:58.531 T:1984951152   DEBUG: Previous line repeats 1 times.
2021-08-03 11:02:58.531 T:1984951152   DEBUG: 1628398800
2021-08-03 11:02:58.542 T:1984951152   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.KeyError'>
                                            Error Contents: u'\u2019'
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.nbcsnliveextra/nbcsn.py", line 263, in <module>
                                                scrape_videos(url)
                                              File "/storage/.kodi/addons/plugin.video.nbcsnliveextra/nbcsn.py", line 74, in scrape_videos
                                                build_video_link(item)
                                              File "/storage/.kodi/addons/plugin.video.nbcsnliveextra/nbcsn.py", line 157, in build_video_link
                                                add_dir(menu_name + ' ' + start_date, '/disabled', 0, imgurl, FANART, False, info)
                                              File "/storage/.kodi/addons/plugin.video.nbcsnliveextra/resources/globals.py", line 229, in add_dir
                                                + "&icon_image=" + urllib.quote_plus(str(icon))
                                              File "/usr/lib/python2.7/urllib.py", line 1303, in quote_plus
                                              File "/usr/lib/python2.7/urllib.py", line 1298, in quote
                                            KeyError: u'\u2019'
                                            -->End of Python script error report<--
2021-08-03 11:02:58.542 T:1984951152   DEBUG: onExecutionDone(110, /storage/.kodi/addons/plugin.video.nbcsnliveextra/nbcsn.py)
2021-08-03 11:02:58.564 T:3011822928   DEBUG: ------ Window Init (DialogNotification.xml) ------
2021-08-03 11:02:58.813 T:1984951152    INFO: Python interpreter stopped
2021-08-03 11:02:58.813 T:1984951152   DEBUG: Thread LanguageInvoker 1984951152 terminating
2021-08-03 11:02:58.821 T:1816130416   ERROR: GetDirectory - Error getting plugin://plugin.video.nbcsnliveextra/?icon_image=http%3a%2f%2fmobileassets.nbcsports.com%2ffiretv%2fchannels%2fnbcolympics-on.png&mode=4&name=Live&url=http%3a%2f%2fapi.leap.nbcsports.com%2ffeed%2fNBCSports%2fnbc-oly%2flive-upcoming%2fv1%2ffiretv
2021-08-03 11:02:58.822 T:1816130416   DEBUG: Thread waiting 1816130416 terminating
2021-08-03 11:02:58.829 T:3011822928   DEBUG: ------ Window Deinit (DialogBusy.xml) ------
2021-08-03 11:02:58.832 T:3011822928   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.nbcsnliveextra/?icon_image=http%3a%2f%2fmobileassets.nbcsports.com%2ffiretv%2fchannels%2fnbcolympics-on.png&mode=4&name=Live&url=http%3a%2f%2fapi.leap.nbcsports.com%2ffeed%2fNBCSports%2fnbc-oly%2flive-upcoming%2fv1%2ffiretv) failed
2021-08-03 11:02:58.833 T:3011822928   DEBUG: CGUIMediaWindow::GetDirectory (plugin://plugin.video.nbcsnliveextra/?icon_image=http%3a%2f%2fmobileassets.nbcsports.com%2ffiretv%2fchannels%2fnbcolympics-on.png&mode=2&name=NBC%20Olympics&url=nbc-olympics)
2021-08-03 11:02:58.833 T:3011822928   DEBUG:   ParentPath = [plugin://plugin.video.nbcsnliveextra/]
2021-08-03 11:02:58.835 T:3011822928   DEBUG: Loading items: 4, directory: plugin://plugin.video.nbcsnliveextra/?icon_image=http%3a%2f%2fmobileassets.nbcsports.com%2ffiretv%2fchannels%2fnbcolympics-on.png&mode=2&name=NBC%20Olympics&url=nbc-olympics sort method: 0, ascending: false
2021-08-03 11:02:58.845 T:1855976304   DEBUG: CAddonDatabase::SetLastUsed[plugin.video.nbcsnliveextra] took 12 ms


--------------------------------------

**Comment by eracknaphobia** [comment]
@jfpark @sachinss123 Please upload links to complete logs by following tutorial [here](https://kodi.wiki/view/Log_file/Easy)

**Comment by jfpark** [comment]
Attached

[kodi.log](https://github.com/eracknaphobia/plugin.video.nbcsnliveextra/files/6930272/kodi.log)

**Comment by eracknaphobia** [comment]
@jfpark I tested the channel on my end and it started fine. Very odd. Are you streaming within the US and not through a proxy or anything similar?

**Comment by jfpark** [comment]
Yes, within the US, with and without VPN, on both a PC and a Libreelec setup on Chromebox. The log was from my PC as it was handy.

**Comment by jfpark** [comment]
Additionally, the Add On will start just fine, able to navigate menus as well. IT's only when selecting something to watch will it throw the error dialog.

**Comment by eracknaphobia** [comment]
Yes, none of those steps care about location or login. Try logging out and back in. Verify your subscription supports the channels you are trying to view.

ex:
![image](https://user-images.githubusercontent.com/8268725/128193893-02dd1d67-16a9-4b20-95d7-aa5c2e6225cb.png)

**Comment by sachinss123** [comment]
Here is my log. I cannot see anything under the Featured / Replays / Highlights/ Clips directories. I'm using a system-wide SOCKS5 proxy connected to a U.S. based server (this is tested and I know it works fine).

Edit: I am able to access all the Olympics live streams using the NBC Sports App - so it is not an issue with the provider login that I'm using.

Another edit: I am able to see and stream the Live channel under 'Olympics'. But that is the only one I can view / stream. This also validates that the proxy is working fine. The v2 log gives the log with the stream. 

Log ending with the listing error:
[kodi.log](https://github.com/eracknaphobia/plugin.video.nbcsnliveextra/files/6932059/kodi.log)

Log ending with the Live Olympics stream:
[kodi v2.log](https://github.com/eracknaphobia/plugin.video.nbcsnliveextra/files/6932093/kodi.v2.log)

**Comment by jfpark** [comment]
Took the additional steps you requested, still no luck. Deauthorized, re-authorized, confirmation message same as yours, still error dialog when trying to view The Olympic Channel

[kodi.log](https://github.com/eracknaphobia/plugin.video.nbcsnliveextra/files/6932114/kodi.log)

**Comment by eracknaphobia** [comment]
@sachinss123 Please test the latest legacy version and let me know.
https://github.com/eracknaphobia/plugin.video.nbcsnliveextra/archive/refs/heads/legacy.zip

**Comment by eracknaphobia** [comment]
Closing stale issue
